### ISSUE TITLE
sorry, please delete this issues!

### ISSUE THREAD

**Issue by Lvellios** [gek64/GitHubDesktopPortable#1]

**Comment by gek64** [comment]
@Lvellios If you want to change the icon of this portable launcher, fork this rope and change `appicon.ico` `appicon_128.png` `appicon_16.png` `appicon_32.png` from `GitHubDesktopPortable/App/AppInfo` to whatever you want, then use the [PortableApps.com Launcher](https://portableapps.com/apps/development/portableapps.com_launcher) to make a new launcher, then copy the new `GitHubDesktopPortable.exe` to previous app folder.

It only changes the launcher's icon, not the GitHubDesktop itself.
