### ISSUE TITLE
[Locate32Portable] Add space to the name

### ISSUE THREAD

**Issue by xmha97** [gek64/GitHubDesktopPortable#3]
Hi, I have a suggestion for [Locate32 Portable](https://github.com/gek64/Locate32Portable)
Please add space to the name.
# Before
```
[Details]
Name=Locate32Portable
```
# After
```
[Details]
Name=Locate32 Portable
```

**Comment by unix755** [comment]
ok https://github.com/gek64/GitHubDesktopPortable/commit/3d74a37b74eba478fa9575c550ba9d075918efa3
