### ISSUE TITLE
Local path folder name

### ISSUE THREAD

**Issue by bakomon** [gek64/GitHubDesktopPortable#4]
Feature Request:

Default folder name on `Local path` from `Github` to `GitHubPortable` when clone or create repository.

![screenshot-2024 01 19-18_47_58](https://github.com/gek64/GitHubDesktopPortable/assets/43160154/451da1f0-4bb2-488d-bd8c-1266ce18cc0f)

**Comment by unix755** [comment]
The portable version only makes Github Desktop a portable application, it cannot add features such as changing the default folder

If you would like Github Desktop to add a feature you need, you can send this feature request at https://github.com/desktop/desktop/issues
