### ISSUE TITLE
Multiple Instances

### ISSUE THREAD

**Issue by JPluess** [gek64/GitHubDesktopPortable#5]
Features Request:

- Multiple Instances Support:

> Allow the ability to run multiple instances of Kodi concurrently, each outputing on a different screen

- Folder Monitoring and Playlist Updates:

> Implement a feature to monitor a specified folder for changes.
> Automatically update the playlist within Kodi when content in the monitored folder changes.

**Comment by unix755** [comment]
- Multiple Instances Support:
The tool that made kodi portable is not a virtual machine, it runs the kodi in your environment and clears all data when you close kodi, if you want to use multiple instances you need kodi itself allow you to do so

- Folder Monitoring and Playlist Updates:
You can send feature requests to https://github.com/xbmc/xbmc/issues
